//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieMasterProject
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class Actor
    {
        public Actor()
        {
            this.MovieActors = new HashSet<MovieActor>();
        }
    
        public int ActorId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string DateOfBirth { get; set; }
        public string Bio { get; set; }
        [NotMapped]
        [Display(Name = "Player Name")]
        public string FullName { get { return FirstName + " " + LastName; } }


    
        public virtual MessageBoardA MessageBoardA { get; set; }
        public virtual ICollection<MovieActor> MovieActors { get; set; }
    }
}
