//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieMasterProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommentA
    {
        public int CommentId { get; set; }
        public string UserName { get; set; }
        public string CommentContents { get; set; }
        public Nullable<int> MessageBoardId { get; set; }
    
        public virtual MessageBoardA MessageBoardA { get; set; }
    }
}
