//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieMasterProject
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class Director
    {
        public Director()
        {
            this.Movies = new HashSet<Movie>();
        }
    
        public int DirectorId { get; set; }
        [DisplayName("Name")]
        public string DirectorName { get; set; }
        [DisplayName("Date of Birth")]
        public string DateOfBirth { get; set; }
        public string Bio { get; set; }
    
        public virtual MessageBoardD MessageBoardD { get; set; }
        public virtual ICollection<Movie> Movies { get; set; }
    }
}
