//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieMasterProject
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class MessageBoardD
    {
        public MessageBoardD()
        {
            this.CommentDs = new HashSet<CommentD>();
        }
    
        public int MessageBoardId { get; set; }
        [DisplayName("Board Name")]
        public string MessageBoardName { get; set; }
    
        public virtual ICollection<CommentD> CommentDs { get; set; }
        public virtual Director Director { get; set; }
    }
}
