//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieMasterProject
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Rating
    {
        public int RatingId { get; set; }
        public string UserName { get; set; }
        public Nullable<int> MovieId { get; set; }
        [DisplayName("Rating")]
       [Range(0, 5, ErrorMessage = "Value must be between 0 and 5.")]
        public Nullable<decimal> Value { get; set; }
    
        public virtual Movie Movie { get; set; }
    }
}
