//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieMasterProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int ReviewId { get; set; }
        public string UserName { get; set; }
        public string ReviewTitle { get; set; }
        public Nullable<decimal> Rating { get; set; }
        public Nullable<int> MessageBoardId { get; set; }
        public string ReviewContents { get; set; }
    
        public virtual MessageBoard MessageBoard { get; set; }
    }
}
